# Generated by Django 5.2.6 on 2025-09-26 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('profile_image_url', models.URLField()),
                ('bio_text', models.TextField(max_length=500)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
